KOD-3.2
rskoczeek/rafal_skoczek-kodilla_tester pull request #13
Opened 2021-08-25 09:53 UTC by rskoczeek

2021-08-25 15:02 UTC, mps4dev requested changes
👎🏻

2021-08-25 15:02 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Shape.java
> +    public int sideA;
klasa Shape ma byc czescia wspolna dla wszystkich figur, ale nie znaczy to, ze ms miec wszystko. Np Square nie ma sideA, sideB, sideC ... po co mu zatem to?

2021-08-25 15:02 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Shape.java
> +    public abstract void getSurfaceArea();
Nie void. Skoro metoda nazywa sie get... to oczekuje, ze cos dostane, tak? Zadne sout w tych metodach, tylko zwracanie policzonej wartosci

2021-08-25 15:02 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework2/Person.java
> +public class Person extends Job {
Person extends Job? Czyli osoba jest zawodem? Czy moze osoba posiada zawod?

2021-09-13 20:50 UTC, rskoczeek commented
Mam tu problem z tym by w PersonApp stworzyć nowy obiekt Person mający parametry: imie, wiek i zawód i wyświetlić obowiązki danego zawodu. Kombinowałem i próbowałem w ten sposób ale utknąłem.

    public static void main(String[] args) {
        Person Aga = new Person("Aga", 32, Teacher);
        Person Karol = new Person("Karol", 44, Plumber);

        Aga.getResponsibilities();
        Karol.getResponsibilities();
    }
}

2021-09-14 13:41 UTC, mps4dev approved these changes

2021-09-15 16:45 UTC, merged