Zadanie KOD 3.8
rskoczeek/rafal_skoczek-kodilla_tester pull request #18
Opened 2021-09-28 17:45 UTC by rskoczeek

Staram się zrobić zadanie KOD 3.8 z bankomatem analogicznie do przykładu z tego rozdziału z dziennikiem ocen. Pogubiłem się jednak i chciałbym omówić to na spotkaniu. Pozdrawiam!

2021-09-28 18:43 UTC, mps4dev requested changes

2021-09-28 18:43 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +    private String maschine;
Tu ma byc tablica bankomatow a nie dwa bankomaty

2021-10-05 17:09 UTC, rskoczeek commented
Dodałem testy do BankTestSuite jednak test bierze pod uwagę tylko ostatni obiekt z tablicy "bank" (takie mam wrażenie) czyli w tym przypadku tylko cashMachine3 i wykonuje na niej operacje.

2021-10-05 20:26 UTC, mps4dev approved these changes

2021-10-06 15:24 UTC, merged